training:
  batch_size: 50000
  n_epochs: 8000
  anneal_power: 2
  mode: joint_learning
  noise_clf: true
  cr_weight: 0.0
  ce_weight: 1.0

# sampling:
#   mode: simple
#   n_steps: 40
#   eps: 1.0
#   decay: 0.9
#   temperature: .3
#   num_samples: 500

sampling:
  mode: anneal
  n_steps_each: 5
  step_lr: 0.000001
  final_only: false
  denoise: true
  verbose: true
  num_samples: 500

data:
  # dir: ./dataset/2024/ood_sl/moon/0_ood
  # dir: ./dataset/2024/ood_sl/roll/noise_100/0
  # dir: ./dataset/2024/ood_sl/circles/noise_010/0
  dir: ./dataset/2024/ood_sl/circles/noise_010/0
  # dir: ./dataset/2024/ood_sl/blobs/5_centers/0
  dim: 2
  channels: 1
  mu: -1
  d_classes: 2

model:
  sigma_begin: 1
  num_classes: 8
  sigma_end: 0.001
  sigma_dist: geometric

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.005
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001